---
sidebar: sidebar 
permalink: use/task-replicate-data.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: Nachdem Sie in der NetApp Console ein FSx für ONTAP -System erstellt oder erkannt haben, können Sie das Dateisystem verwalten und NetApp Datendienste verwenden, die Funktionen wie Sicherung und Wiederherstellung bereitstellen. 
---
= FSx for ONTAP Daten in der NetApp Console replizieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Replizieren Sie Daten, um sich gegen Datenverlust zu schützen, falls in der Region, in der sich Ihre Daten befinden, eine Katastrophe eintritt. Die Datenreplikation wird zwischen FSx for ONTAP Dateisystemen und lokalen ONTAP Systemen oder Cloud Volumes ONTAP unterstützt.

.Informationen zu diesem Vorgang
Dieser Vorgang erstellt eine Replikationsbeziehung für Quell-Volumes in einem FSx for ONTAP Dateisystem, einem On-Premises ONTAP System oder Cloud Volumes ONTAP System.

Replizierte Volumes im Zieldateisystem sind Data Protection (DP) Volumes und folgen dem Namensformat: `{OriginalVolumeName}_copy`.

.Bevor Sie beginnen
Beachten Sie Folgendes, bevor Sie beginnen.

* Um Daten zwischen FSx for ONTAP und On-Premises ONTAP oder Cloud Volumes ONTAP zu replizieren, müssen Sie einen Console-Agenten mit Konnektivität zum Dateisystem auswählen oder das Dateisystem eingeben, um eine Verknüpfung herzustellen. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Erfahren Sie mehr über die Verwendung von Links"^]
* Die Replikation wird nicht unterstützt für Volumes, die sich in einem anderen Status als verfügbar, erstellt oder falsch konfiguriert befinden, und wenn die ONTAP-Version nicht kompatibel ist.


.Schritte
. Ziehen Sie auf der NetApp Console Systems-Seite das Quell-FSx for ONTAP-Dateisystem, das lokale ONTAP-System oder Cloud Volumes ONTAP-System auf das Ziel-FSx for ONTAP-Dateisystem und wählen Sie *Replikation* aus.
. Wählen Sie auf der Seite „Replikation erstellen“ die zu replizierenden Quellvolumes aus und klicken Sie dann auf *Weiter*.
. Geben Sie unter Replikationsziel Folgendes an:
+
.. *Zielname*: Sie haben den Zielnamen angewendet, als Sie das Quell-Storage-System auf das Zielsystem auf der Seite Console Systems per Drag & Drop gezogen haben.
.. *Anwendungsfall*: Wählen Sie einen der folgenden Anwendungsfälle für die Replikation aus.  Abhängig vom ausgewählten Anwendungsfall füllt Workload Factory das Formular gemäß Best Practices mit empfohlenen Werten aus.  Sie können die empfohlenen Werte akzeptieren oder beim Ausfüllen des Formulars Änderungen vornehmen.
+
*** Migration: Überträgt Ihre Daten auf das Ziel-FSx für ONTAP -Dateisystem
*** Hot Disaster Recovery: gewährleistet hohe Verfügbarkeit und schnelle Disaster Recovery für kritische Workloads
*** Kalte oder Archiv-Notfallwiederherstellung:
+
**** Cold Disaster Recovery: nutzt längere Recovery Time Objectives (RTO) und Recovery Point Objectives (RPO), um die Kosten zu senken
**** Archiv: Repliziert Daten für die langfristige Speicherung und Compliance


*** Sonstige
+
Darüber hinaus bestimmt die Auswahl des Anwendungsfalls die Replikationsrichtlinie oder SnapMirror -Richtlinie (ONTAP).  Die zur Beschreibung von Replikationsrichtlinien verwendeten Begriffe stammen auslink:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["ONTAP 9 Dokumentation"^] .

+
**** Für Migration und andere Zwecke heißt die Replikationsrichtlinie _MirrorAllSnapshots_.  _MirrorAllSnapshots_ ist eine asynchrone Richtlinie zum Spiegeln aller Snapshots und des neuesten aktiven Dateisystems.
**** Für die Notfallwiederherstellung im Hot-, Cold- oder Archivmodus heißt die Replikationsrichtlinie _MirrorAndVault_.  _MirrorAndVault_ ist eine asynchrone Vault-Richtlinie zum Spiegeln des neuesten aktiven Dateisystems und täglicher und wöchentlicher Snapshots.
+
Wenn Sie Snapshots für die langfristige Aufbewahrung aktivieren, lautet die Standardreplikationsrichtlinie für alle Anwendungsfälle _MirrorAndVault_.





.. *FSx for ONTAP file system*: Wählen Sie Anmeldeinformationen, Region und FSx for ONTAP file system name für das Ziel-FSx for ONTAP file system aus.
.. *Name der Speicher-VM*: Wählen Sie die Speicher-VM aus dem Dropdown-Menü aus.  Die von Ihnen ausgewählte Speicher-VM ist das Ziel für alle ausgewählten Volumes in dieser Replikationsbeziehung.
.. *Volumename*: Der Zielvolumename wird automatisch im folgenden Format generiert `{OriginalVolumeName}_copy` .  Sie können den automatisch generierten Datenträgernamen verwenden oder einen anderen Datenträgernamen eingeben.
.. *Tiering-Richtlinie*: Wählen Sie die Tiering-Richtlinie für die im Zielvolume gespeicherten Daten aus.  Die Tiering-Richtlinie entspricht standardmäßig der empfohlenen Tiering-Richtlinie für den von Ihnen ausgewählten Anwendungsfall.
+
_Ausgeglichen (Auto)_ ist die Standard-Tiering-Richtlinie beim Erstellen eines Volumes mit der Workload Factory-Konsole.  Weitere Informationen zu Volume-Tiering-Richtlinien finden Sie unterlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Volume-Speicherkapazität"^] in der AWS FSx für NetApp ONTAP -Dokumentation.  Beachten Sie, dass Workload Factory in der Workload Factory-Konsole anwendungsfallbasierte Namen für Tiering-Richtlinien verwendet und FSx für ONTAP -Tiering-Richtliniennamen in Klammern einschließt.

+
Wenn Sie den Migrationsanwendungsfall ausgewählt haben, wählt Workload Factory automatisch aus, dass die Tiering-Richtlinie des Quellvolumes auf das Zielvolume kopiert werden soll.  Sie können die Option zum Kopieren der Tiering-Richtlinie deaktivieren und eine Tiering-Richtlinie auswählen, die für das für die Replikation ausgewählte Volume gilt.

.. *Maximale Übertragungsrate*: Wählen Sie *Begrenzt* und geben Sie das maximale Übertragungslimit in MB/s ein.  Alternativ können Sie *Unbegrenzt* auswählen.
+
Ohne Begrenzung kann die Netzwerk- und Anwendungsleistung nachlassen.  Alternativ empfehlen wir eine unbegrenzte Übertragungsrate für FSx for ONTAP -Dateisysteme für kritische Workloads, beispielsweise solche, die hauptsächlich für die Notfallwiederherstellung verwendet werden.



. Geben Sie unter „Replikationseinstellungen“ Folgendes an:
+
.. *Replikationsintervall*: Wählen Sie die Häufigkeit aus, mit der Snapshots vom Quellvolume auf das Zielvolume übertragen werden.
.. *Langzeitaufbewahrung*: Aktivieren Sie optional Snapshots für die Langzeitaufbewahrung.  Durch die langfristige Aufbewahrung können Geschäftsdienste auch bei einem vollständigen Site-Ausfall weiter ausgeführt werden, und Anwendungen können mithilfe einer sekundären Kopie transparent ausfallen.
+
Replikationen ohne langfristige Aufbewahrung verwenden die Richtlinie _MirrorAllSnapshots_.  Durch die Aktivierung der langfristigen Aufbewahrung wird der Replikation die Richtlinie _MirrorAndVault_ zugewiesen.

+
Wenn Sie die langfristige Aufbewahrung aktivieren, wählen Sie eine vorhandene Richtlinie aus oder erstellen Sie eine neue Richtlinie, um die zu replizierenden Snapshots und die aufzubewahrende Anzahl zu definieren.

+

NOTE: Für eine langfristige Aufbewahrung sind übereinstimmende Quell- und Zielbezeichnungen erforderlich.  Auf Wunsch kann Workload Factory fehlende Labels für Sie erstellen.

+
*** *Wählen Sie eine vorhandene Richtlinie*: Wählen Sie eine vorhandene Richtlinie aus dem Dropdown-Menü aus.
*** *Neue Richtlinie erstellen*: Geben Sie einen *Richtliniennamen* ein.


.. *Unveränderliche Snapshots*: Optional.  Wählen Sie *Unveränderliche Snapshots aktivieren* aus, um zu verhindern, dass in dieser Richtlinie erstellte Snapshots während der Aufbewahrungsfrist gelöscht werden.
+
*** Legen Sie die *Aufbewahrungsdauer* in Stunden, Tagen, Monaten oder Jahren fest.
*** *Snapshot-Richtlinien*: Wählen Sie in der Tabelle die Häufigkeit der Snapshot-Richtlinie und die Anzahl der aufzubewahrenden Kopien aus.  Sie können mehr als eine Snapshot-Richtlinie auswählen.


.. *S3-Zugriffspunkt*: Optional können Sie einen S3-Zugriffspunkt anbinden, um auf FSx for ONTAP-Dateisystemdaten zuzugreifen, die sich auf NFS- oder SMB/CIFS-Volumes befinden, über die AWS S3-APIs. Nur der Dateizugriffstyp wird unterstützt. Folgende Details sind anzugeben:
+
*** *Name des S3 access point*: Geben Sie den Namen des S3 access point ein.
*** *Benutzer*: Wählen Sie einen vorhandenen Benutzer mit Zugriff auf das Volume aus oder erstellen Sie einen neuen Benutzer.
*** *Benutzertyp*: Wählen Sie *UNIX* oder *Windows* als Benutzerart.
*** *Netzwerkkonfiguration*: Wählen Sie *Internet* oder *Virtual private cloud (VPC)*. Der von Ihnen gewählte Netzwerktyp bestimmt, ob der Zugangspunkt aus dem Internet erreichbar ist oder auf eine bestimmte VPC beschränkt ist.
*** *Metadaten aktivieren*: Durch die Aktivierung von Metadaten wird eine S3-Tabelle erstellt, die alle über den S3-Zugangspunkt zugänglichen Objekte enthält, die Sie für Audits, Governance, Automatisierung, Analyse und Optimierung verwenden können. Die Aktivierung von Metadaten verursacht zusätzliche AWS-Kosten. Weitere Informationen finden Sie unter link:https://aws.amazon.com/s3/pricing/["Amazon S3 Preisdokumentation"^].


.. *S3 access point tags*: Optional können Sie bis zu 50 Tags hinzufügen.




. Wählen Sie *Erstellen*.

